# Generated by Django 4.2 on 2023-04-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzapp', '0002_alter_category_budget_alter_user_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='budget',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
