# Generated by Django 4.2 on 2023-04-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzapp', '0003_alter_user_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
