# Generated by Django 4.2 on 2023-04-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzapp', '0004_user_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='amount',
            new_name='total',
        ),
    ]
